### PR TITLE
Updates for the new content app on 'master'

### PR DESCRIPTION
**Pull request by bmbouter**
This updates Travis to continue to pass given the breaking change
merged to core with this PR: https://github.com/pulp/pulp/pull/3779

### CODE REVIEW

**Comment by bmbouter** [comment]
@mdellweg  This is for the upcoming breaking changes by the Content app becoming an aiohttp application that runs as a separate service.

**Comment by bmbouter** [comment]
Tests are failing waiting on a PyPI release:  https://github.com/PulpQE/pulp-smash/pull/1156#issuecomment-447407977

**Comment by bmbouter** [comment]
@mdellweg The pulp-smash changes were released so now I think it's only failing due to the strange error where it checks out a PR that doesn't exist on the 3.6 test. I'm not sure why its doing that. Do you know?

**Comment by mdellweg** [comment]
@bmbouter That means, the call to the github api worked (i have the impression, that it is not dependable...)
In short, it extracts the pulp-PR to test against from the text in the PR, not the (last) commit message.
You can either remove the reference to 'pulp/pulp#3779', or (which might be better) add 'requires' to the regex searching for it.
I know, that i changed the travis machinery a little bit to what i think is better (i.e. not sourcing the scripts). Maybe, you want to take a closer look.

**Comment by mdellweg** [comment]
@bmbouter would you mind, signing the commit?

**Comment by mdellweg** [comment]
BTW: Thank you for keeping this repo up with the changes.

**Comment by mdellweg** [comment]
See #15

**Comment by mdellweg** [comment]
I incorporated this fix in #15 therfore closing this one.
Thank you very much.

**Comment by bmbouter** [comment]
@mdellweg thanks for that. It's been kind of crazy wrapping things up at the end of the year here.

**Pull request closed without merging**
